name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - id: build-publish
        uses: bitovi/github-actions-react-to-ghp@v1.2.2
        with:
          path: storybook-static
          build_command: npm run build-storybook
